sudo: required
services:
  - docker

before_install:
  - docker build -t saveup/saveup-backend .

script:
  - docker run saveup/saveup-backend ./mvnw test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "SAVEUP_BACKEND"
  env: "Saveupbackend-env"
  bucket_name: "elasticbeanstalk-us-east-2-855433857104"
  bucket_path: "saveupbackend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
