version: '3'
services:
  saveup-backend:
    build: .
    ports:
      - 80:8080
    container_name: 'saveupbackend'
    environment:
      - SPRING_PROFILES_ACTIVE
      - BD_URL
      - BD_USERNAME
      - BD_PASSWORD
      - SERVER_PORT=8080
