version: '3'
services:
    saveup-backend:
        build: .
        container_name: 'saveupbackend'
        ports:
        -   80:8080
        environment:
            - SPRING_PROFILES_ACTIVE
            - BD_USERNAME
            - BD_PASSWORD
            - AWS_ACCESS_KEY
            - AWS_SECRET_KEY