version: '3'
services:
    saveup-backend:
        build: .
        ports:
          - 8080:8080
        expose:
          - 8080
        container_name: 'saveupbackend'
        environment:
            - SPRING_PROFILES_ACTIVE
            - BD_URL
            - BD_USERNAME
            - BD_PASSWORD
