spring:
  datasource:
    url: jdbc:postgresql://aa7dwqgfalbuyh.cgbxwxzwzocn.us-east-2.rds.amazonaws.com:5432/postgres
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
saveup:
  aws-access-key-id: ${AWS_ACCESS_KEY}
  aws-secret-key: ${AWS_SECRET_KEY}
  bucket-name: saveup-storage
  origin-permitida: ${ORIGIN:http://localhost:4200}