spring:
  datasource:
    url: jdbc:postgresql://${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
saveup:
  aws-access-key-id: AKIA4OK6UZBIGHGL7LUY
  aws-secret-key: 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
  bucket-name: saveup-storage
  origin-permitida: ${ORIGIN:http://localhost:4200}